// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: agents.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAgent = `-- name: CreateAgent :exec
INSERT INTO agents (id, name, token, user_id, reset_datetime)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAgentParams struct {
	ID            uuid.UUID     `json:"id"`
	Name          string        `json:"name"`
	Token         string        `json:"token"`
	UserID        uuid.UUID     `json:"user_id"`
	ResetDatetime sql.NullInt32 `json:"reset_datetime"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) error {
	_, err := q.db.ExecContext(ctx, createAgent,
		arg.ID,
		arg.Name,
		arg.Token,
		arg.UserID,
		arg.ResetDatetime,
	)
	return err
}

const deleteAgentById = `-- name: DeleteAgentById :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgentById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAgentById, id)
	return err
}

const getAgentTokenById = `-- name: GetAgentTokenById :one
SELECT token FROM agents WHERE id = $1
`

func (q *Queries) GetAgentTokenById(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getAgentTokenById, id)
	var token string
	err := row.Scan(&token)
	return token, err
}

const getAgentsByUserId = `-- name: GetAgentsByUserId :many
SELECT id, name, reset_datetime FROM agents WHERE user_id = $1
`

type GetAgentsByUserIdRow struct {
	ID            uuid.UUID     `json:"id"`
	Name          string        `json:"name"`
	ResetDatetime sql.NullInt32 `json:"reset_datetime"`
}

func (q *Queries) GetAgentsByUserId(ctx context.Context, userID uuid.UUID) ([]GetAgentsByUserIdRow, error) {
	rows, err := q.db.QueryContext(ctx, getAgentsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAgentsByUserIdRow
	for rows.Next() {
		var i GetAgentsByUserIdRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ResetDatetime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
